include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    # Ignore generated files
    - "**/*.g.dart"
    - "lib/generated/**"
    - "lib/models/**"
  errors:
    close_sinks: ignore
linter:
  rules:
    unsafe_html: false
